name: Run Java Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
      - name: Compile code
        run: javac -d out src/test/randooptests/*.java
      - name: Run Randoop Tests
        run: java -cp "out:src/test/randooptests" org.junit.runner.JUnitCore test.randooptests.Book_Randoop